first spider
zain14shah/demo pull request #2
Opened 2018-11-01 14:14 UTC by zain14shah

2018-11-06 07:34 UTC, hamza-jutt requested changes
Data extracted should not contain tags unless required (That usually never happens). Why is there commented lines in final revision? Fix the issues.

2018-11-13 08:25 UTC, zain14shah commented
Having an issue applying enumerate().
![enumerate](https://user-images.githubusercontent.com/43273101/48400232-9eefa580-e747-11e8-8845-9c46324f67fd.png)

2018-11-14 14:12 UTC, hamza-jutt requested changes
Read the docs for enumerate issue that you are facing and update the code.

2018-11-14 14:12 UTC, hamza-jutt commented on prayers_timings.py
> +                './/td/strong/text()').extract_first()
can be on same line

2018-11-14 14:12 UTC, hamza-jutt commented on prayers_timings.py
> +            '//table[@class ="table  table-bordered table-striped"]//th/text()').extract()[1:]
A better formatting that looks clean can be 
```
function_name(
    'lengthy_argument_1', 'lengthy_argument_2'
)
```

2018-11-14 14:12 UTC, hamza-jutt commented on prayers_timings.py
> +            index = 0
use enumerate to maintain indexes.

2018-11-14 14:12 UTC, hamza-jutt commented on prayers_timings.py
> +                prayers.update({name: all_prayer_timings[index]})
can use `prayers[name] = all_prayer_timings[index]`

2018-11-14 14:12 UTC, hamza-jutt commented on prayers_timings.py
> +            yield ({city_name: prayers})
can be `yield {city_name: prayers}`

2018-11-14 14:12 UTC, hamza-jutt commented on prayers_timings.py
> +            prayers = {}
shoud be `prayer_timings = {}`

2018-11-19 12:06 UTC, hamza-jutt approved these changes

2019-01-02 12:31 UTC, merged